[package]
name = "egui-toast"
description = "Toast notifications for the egui library"
version = "0.8.1"
authors = ["Urho Laukkarinen <urho.laukkarinen@gmail.com>"]
edition = "2021"

license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/urholaukkarinen/egui-toast"
repository = "https://github.com/urholaukkarinen/egui-toast"
categories = ["gui"]
keywords = ["egui", "toast", "notification"]

[workspace]
members = ["demo"]

[dependencies]
egui = { path = "../egui/crates/egui", default-features = false }
# egui = { version = "0.22.0", default-features = false }

[profile.release]
opt-level = 2
